import js from '@eslint/js'
import stylistic from '@stylistic/eslint-plugin'
import imports from 'eslint-plugin-import-x'
import node from 'eslint-plugin-n'
import promise from 'eslint-plugin-promise'
import regexp from 'eslint-plugin-regexp'
import sort from 'eslint-plugin-simple-import-sort'
import unicorn from 'eslint-plugin-unicorn'
import globals from 'globals'

export default [
  { ignores: ['dist/**', 'releases/**', 'node_modules/**'] },
  {
    files: ['src/**/*.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.node,
        chrome: 'readonly',
        browser: 'readonly',
      },
    },
    linterOptions: { reportUnusedDisableDirectives: 'error' },
    plugins: {
      '@stylistic': stylistic,
      'import-x': imports,
      n: node,
      promise,
      regexp,
      'simple-import-sort': sort,
      unicorn,
    },
    settings: {
      'import-x/resolver': { node: { extensions: ['.js', '.json'] } },
      'import-x/ignore': ['node_modules', '\\.(css|svg|json)$'],
    },
    // Keep the existing checks; use maintained rules for deprecated checks.
    rules: {
      ...js.configs.recommended.rules,
      '@stylistic/max-len': [
        'error',
        {
          code: 80,
          ignoreComments: true,
          ignoreStrings: true,
          ignoreTemplateLiterals: true,
          ignoreRegExpLiterals: true,
        },
      ],
      'simple-import-sort/imports': 'error',
      'simple-import-sort/exports': 'error',
      '@stylistic/brace-style': ['error', '1tbs'],
      '@stylistic/no-multi-spaces': ['error', { ignoreEOLComments: false }],
      '@stylistic/padding-line-between-statements': [
        'error',
        { blankLine: 'always', prev: ['const', 'let', 'var'], next: '*' },
        {
          blankLine: 'any',
          prev: ['const', 'let', 'var'],
          next: ['const', 'let', 'var'],
        },
        { blankLine: 'always', prev: 'directive', next: '*' },
        { blankLine: 'always', prev: '*', next: 'directive' },
      ],
      curly: ['error', 'all'],
      '@stylistic/comma-dangle': ['error', 'always-multiline'],
      'id-length': ['error', { min: 2, exceptions: ['i', 'x', 'y', 'e'] }],
      'id-match': [
        'error',
        '^(([A-Za-z0-9]+){2,})|([A-Z][A-Z_0-9]+)$',
        {
          properties: false,
          onlyDeclarations: true,
          ignoreDestructuring: false,
        },
      ],
      '@stylistic/indent': [
        'error',
        2,
        { SwitchCase: 1, flatTernaryExpressions: false, ignoreComments: false },
      ],
      '@stylistic/quotes': ['error', 'single'],
      '@stylistic/semi': ['error', 'never'],
      'accessor-pairs': 'error',
      '@stylistic/array-bracket-spacing': ['error', 'never'],
      '@stylistic/arrow-spacing': ['error', { before: true, after: true }],
      '@stylistic/block-spacing': ['error', 'always'],
      camelcase: [
        'error',
        {
          properties: 'never',
          ignoreDestructuring: false,
          ignoreImports: false,
        },
      ],
      '@stylistic/comma-spacing': ['error', { before: false, after: true }],
      '@stylistic/comma-style': ['error', 'last'],
      '@stylistic/computed-property-spacing': ['error', 'never'],
      'constructor-super': 'error',
      '@stylistic/dot-location': ['error', 'property'],
      'dot-notation': ['error', { allowKeywords: true, allowPattern: '' }],
      '@stylistic/eol-last': ['error', 'always'],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      '@stylistic/function-call-spacing': ['error', 'never'],
      '@stylistic/generator-star-spacing': [
        'error',
        { before: true, after: true },
      ],
      'n/handle-callback-err': ['error', '^(err|error)$'],
      '@stylistic/key-spacing': [
        'error',
        { beforeColon: false, afterColon: true },
      ],
      '@stylistic/keyword-spacing': ['error', { before: true, after: true }],
      '@stylistic/lines-between-class-members': [
        'error',
        'always',
        { exceptAfterSingleLine: true },
      ],
      '@stylistic/new-parens': 'error',
      'no-array-constructor': 'error',
      'no-async-promise-executor': 'error',
      'no-caller': 'error',
      'no-case-declarations': 'error',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': ['error', 'always'],
      'no-const-assign': 'error',
      'no-constant-condition': ['error', { checkLoops: false }],
      'no-control-regex': 'error',
      'no-debugger': 'error',
      'no-delete-var': 'error',
      'no-dupe-args': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-empty-character-class': 'error',
      'no-empty-pattern': 'error',
      'no-eval': 'error',
      'no-ex-assign': 'error',
      'no-extend-native': 'error',
      'no-extra-bind': 'error',
      'no-extra-boolean-cast': 'error',
      '@stylistic/no-extra-parens': ['error', 'functions'],
      'no-fallthrough': 'error',
      '@stylistic/no-floating-decimal': 'error',
      'no-func-assign': 'error',
      'no-global-assign': ['error', { exceptions: [] }],
      'no-implied-eval': 'error',
      'no-inner-declarations': ['error', 'functions'],
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': 'error',
      'no-iterator': 'error',
      'no-labels': ['error', { allowLoop: false, allowSwitch: false }],
      'no-lone-blocks': 'error',
      'no-misleading-character-class': 'error',
      'no-prototype-builtins': 'error',
      'no-useless-catch': 'error',
      '@stylistic/no-mixed-operators': [
        'error',
        {
          groups: [
            ['==', '!=', '===', '!==', '>', '>=', '<', '<='],
            ['&&', '||'],
            ['in', 'instanceof'],
          ],
          allowSamePrecedence: true,
        },
      ],
      '@stylistic/no-mixed-spaces-and-tabs': 'error',
      'no-multi-str': 'error',
      '@stylistic/no-multiple-empty-lines': ['error', { max: 1, maxEOF: 0 }],
      'no-unsafe-negation': 'error',
      'no-new': 'error',
      'no-new-func': 'error',
      'no-object-constructor': 'error',
      'n/no-new-require': 'error',
      'no-new-native-nonconstructor': 'error',
      'no-new-wrappers': 'error',
      'no-obj-calls': 'error',
      'no-octal': 'error',
      'no-octal-escape': 'error',
      'n/no-path-concat': 'error',
      'no-proto': 'error',
      'no-redeclare': ['error', { builtinGlobals: false }],
      'no-regex-spaces': 'error',
      'no-return-assign': ['error', 'except-parens'],
      'no-self-assign': ['error', { props: true }],
      'no-self-compare': 'error',
      'no-sequences': 'error',
      'no-shadow-restricted-names': 'error',
      'no-sparse-arrays': 'error',
      '@stylistic/no-tabs': 'error',
      'no-template-curly-in-string': 'error',
      'no-this-before-super': 'error',
      'no-throw-literal': 'error',
      '@stylistic/no-trailing-spaces': [
        'error',
        { skipBlankLines: false, ignoreComments: false },
      ],
      'no-undef': 'error',
      'no-undef-init': 'error',
      'no-unexpected-multiline': 'error',
      'no-unmodified-loop-condition': 'error',
      'no-unneeded-ternary': ['error', { defaultAssignment: false }],
      'no-unreachable': 'error',
      'no-unsafe-finally': 'error',
      'no-unused-expressions': [
        'error',
        {
          allowShortCircuit: true,
          allowTernary: true,
          allowTaggedTemplates: true,
        },
      ],
      'no-unused-vars': [
        'error',
        {
          vars: 'all',
          args: 'none',
          ignoreRestSiblings: true,
          caughtErrors: 'none',
        },
      ],
      'no-use-before-define': [
        'error',
        { functions: false, classes: false, variables: false },
      ],
      'no-useless-call': 'error',
      'no-useless-computed-key': 'error',
      'no-useless-constructor': 'error',
      'no-useless-escape': 'error',
      'no-useless-rename': [
        'error',
        {
          ignoreDestructuring: false,
          ignoreImport: false,
          ignoreExport: false,
        },
      ],
      'no-useless-return': 'error',
      'no-void': 'error',
      '@stylistic/no-whitespace-before-property': 'error',
      'no-with': 'error',
      '@stylistic/object-curly-newline': [
        'error',
        { multiline: true, consistent: true },
      ],
      '@stylistic/object-curly-spacing': ['error', 'always'],
      '@stylistic/object-property-newline': [
        'error',
        { allowAllPropertiesOnSameLine: true },
      ],
      'one-var': ['error', { initialized: 'never' }],
      '@stylistic/operator-linebreak': [
        'error',
        'after',
        { overrides: { '?': 'before', ':': 'before', '|>': 'before' } },
      ],
      '@stylistic/padded-blocks': [
        'error',
        { blocks: 'never', switches: 'never', classes: 'never' },
      ],
      'prefer-const': [
        'error',
        { destructuring: 'all', ignoreReadBeforeAssign: false },
      ],
      'prefer-promise-reject-errors': ['error', { allowEmptyReject: true }],
      '@stylistic/quote-props': ['error', 'as-needed'],
      '@stylistic/rest-spread-spacing': ['error', 'never'],
      '@stylistic/semi-spacing': ['error', { before: false, after: true }],
      '@stylistic/space-before-blocks': ['error', 'always'],
      '@stylistic/space-before-function-paren': ['error', 'always'],
      '@stylistic/space-in-parens': ['error', 'never'],
      '@stylistic/space-infix-ops': 'error',
      '@stylistic/space-unary-ops': ['error', { words: true, nonwords: false }],
      '@stylistic/spaced-comment': [
        'error',
        'always',
        {
          line: { markers: ['*package', '!', '/', ',', '='] },
          block: {
            balanced: true,
            markers: ['*package', '!', ',', ':', '::', 'flow-include'],
            exceptions: ['*'],
          },
        },
      ],
      'symbol-description': 'error',
      '@stylistic/template-curly-spacing': ['error', 'never'],
      '@stylistic/template-tag-spacing': ['error', 'never'],
      'unicode-bom': ['error', 'never'],
      'use-isnan': 'error',
      'valid-typeof': ['error', { requireStringLiterals: true }],
      '@stylistic/wrap-iife': [
        'error',
        'any',
        { functionPrototypeMethods: true },
      ],
      '@stylistic/yield-star-spacing': ['error', 'both'],
      yoda: ['error', 'never'],
      'import-x/export': 'error',
      'import-x/first': 'error',
      'import-x/no-absolute-path': [
        'error',
        { esmodule: true, commonjs: true, amd: false },
      ],
      'import-x/no-duplicates': 'error',
      'import-x/no-named-default': 'error',
      'import-x/no-webpack-loader-syntax': 'error',
      'n/no-deprecated-api': 'error',
      'n/process-exit-as-throw': 'error',
      'promise/param-names': 'error',
      'n/no-callback-literal': 'error',
      '@stylistic/arrow-parens': ['error', 'always'],
      'import-x/no-self-import': 'error',
      'import-x/order': [
        'error',
        {
          groups: [
            ['builtin', 'external'],
            ['internal', 'parent'],
            ['sibling', 'index'],
          ],
          'newlines-between': 'ignore',
        },
      ],
      'import-x/newline-after-import': ['error', { count: 1 }],
      'unicorn/catch-error-name': ['error', { name: 'error', ignore: ['^_'] }],
      'unicorn/explicit-length-check': 'error',
      'unicorn/no-abusive-eslint-disable': 'error',
      'unicorn/no-process-exit': 'error',
      'unicorn/throw-new-error': 'error',
      'unicorn/number-literal-case': 'error',
      'unicorn/escape-case': 'error',
      'unicorn/no-instanceof-builtins': 'error',
      'unicorn/no-new-buffer': 'error',
      'unicorn/prefer-unicode-code-point-escapes': 'error',
      'unicorn/prefer-string-starts-ends-with': 'error',
      'unicorn/prefer-type-error': 'error',
      'unicorn/new-for-builtins': 'error',
      'regexp/prefer-d': 'error',
      'regexp/prefer-w': 'error',
      'unicorn/error-message': 'error',
      'unicorn/prefer-add-event-listener': 'error',
      'prefer-exponentiation-operator': 'error',
      'unicorn/no-console-spaces': 'error',
      'unicorn/no-unreadable-array-destructuring': 'error',
      'unicorn/prefer-dom-node-append': 'error',
      'import-x/named': 'error',
      'import-x/no-named-as-default-member': 'error',
      'import-x/no-extraneous-dependencies': [
        'error',
        { devDependencies: false, optionalDependencies: false },
      ],
      'import-x/no-mutable-exports': 'error',
      'import-x/no-amd': 'error',
      'import-x/extensions': [
        'error',
        'ignorePackages',
        { js: 'never', mjs: 'never', jsx: 'never' },
      ],
      'import-x/no-dynamic-require': 'error',
      'import-x/no-useless-path-segments': 'error',
      'no-var': 'error',
      'object-shorthand': [
        'error',
        'always',
        { ignoreConstructors: false, avoidQuotes: true },
      ],
      'prefer-numeric-literals': 'error',
      'prefer-spread': 'error',
      'prefer-template': 'error',
      'require-yield': 'error',
      'no-label-var': 'error',
      'no-shadow': 'error',
      'func-names': 'error',
      'no-bitwise': 'error',
      'no-lonely-if': 'error',
      'no-multi-assign': 'error',
      'no-nested-ternary': 'error',
      'operator-assignment': ['error', 'always'],
      'n/global-require': 'error',
      'for-direction': 'error',
      'getter-return': ['error', { allowImplicit: true }],
      'no-empty': 'error',
      'array-callback-return': ['error', { allowImplicit: true }],
      'block-scoped-var': 'error',
      'consistent-return': 'error',
      'default-case': ['error', { commentPattern: '^no default$' }],
      'guard-for-in': 'error',
      'no-alert': 'error',
      'no-else-return': ['error', { allowElseIf: false }],
      'no-empty-function': [
        'error',
        { allow: ['arrowFunctions', 'functions', 'methods'] },
      ],
      'no-extra-label': 'error',
      'no-loop-func': 'error',
      'no-restricted-properties': [
        'error',
        {
          object: 'arguments',
          property: 'callee',
          message: 'arguments.callee is deprecated',
        },
        {
          object: 'global',
          property: 'isFinite',
          message: 'Please use Number.isFinite instead',
        },
        {
          object: 'self',
          property: 'isFinite',
          message: 'Please use Number.isFinite instead',
        },
        {
          object: 'window',
          property: 'isFinite',
          message: 'Please use Number.isFinite instead',
        },
        {
          object: 'global',
          property: 'isNaN',
          message: 'Please use Number.isNaN instead',
        },
        {
          object: 'self',
          property: 'isNaN',
          message: 'Please use Number.isNaN instead',
        },
        {
          object: 'window',
          property: 'isNaN',
          message: 'Please use Number.isNaN instead',
        },
        {
          property: '__defineGetter__',
          message: 'Please use Object.defineProperty instead.',
        },
        {
          property: '__defineSetter__',
          message: 'Please use Object.defineProperty instead.',
        },
        {
          object: 'Math',
          property: 'pow',
          message: 'Use the exponentiation operator (**) instead.',
        },
      ],
      'no-script-url': 'error',
      'no-unused-labels': 'error',
      'no-useless-concat': 'error',
      radix: 'error',
    },
  },
]
