name: Build

on: [push]

jobs:
  build:
    name: Test on Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24]

    steps:
    - uses: actions/checkout@v7.0.1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v7.0.0
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
    - run: npm ci
    - run: npm test
    - run: npm run lint
    - run: npm run stylelint
    - run: npm run build:chrome:prod
    - run: npm run build:firefox:prod
    - run: npm run locales:check
      env:
        CI: true
        PROJECT_NAME: censortracker
    - name: Upload Chrome extension
      uses: actions/upload-artifact@v7.0.1
      with:
        name: censortracker-chrome-${{ github.sha }}
        path: dist/chrome/prod/
        if-no-files-found: error
    - name: Upload Firefox extension
      uses: actions/upload-artifact@v7.0.1
      with:
        name: censortracker-firefox-${{ github.sha }}
        path: dist/firefox/prod/
        if-no-files-found: error
